### PR TITLE
Introduce Error Handling for createChatCompletion() thread

### LINKED ISSUE #35: Introduce Error Handling for `createChatCompletion`
Recently, we are getting errors from OpenAI API which result in non gracefully exited threads. IMO it would be great to introduce some simple error handling like described in https://www.npmjs.com/package/openai?activeTab=readme#Usage

Working on this right now. Pull request will follow.

### PR DESCRIPTION
**Pull request by your-highness**
Closes #35

### CODE REVIEW

**Comment by your-highness** [comment]
Any idead when it will be merged?

**Comment by yGuy** [comment]
Can you describe the effect of this PR? How exactly did it improve the situation for you?Before: crash, stacktrace, restart.After: crash, log error, continue. What else?Do you get better error messages this way?
-------- Ursprüngliche Nachricht --------Von: Johannes Helmuth ***@***.***> Datum: 01.06.23  15:09  (GMT+06:00) An: yGuy/chatgpt-mattermost-bot ***@***.***> Cc: Subscribed ***@***.***> Betreff: Re: [yGuy/chatgpt-mattermost-bot] Introduce Error Handling for createChatCompletion() thread (PR #40) 
Any idead when it will be merged?

**Comment by your-highness** [comment]
The log output indicates now that the chat completion did not work properly. Before it was not giving any output at all if case of crashing threads.

**Comment by yGuy** [comment]
OK. Please update to not just error the status and message, but format all of the available information into a single status and message error. Include a text that describes the location of the error. Like "error from openai response: status: .. message: ..."

**Pull request closed without merging**
