### PR TITLE
Fix to work with Mattermost installed in Subpath

### LINKED ISSUE #18: Not work if Mattermost is installed on Subpath.
### Overview
This tool will not work if Mattermost is installed on Subpath.

### Example
```
$ sudo head -3 /opt/mattermost/config/config.json
{
    "ServiceSettings": {
        "SiteURL": "http://localhost:8065/mattermost",

$ export MATTERMOST_URL=http://localhost:8065/mattermost
$ node src/botservice.js

websocket connecting to ws://localhost:8065/api/v4/websocket
{"level":"INFO","name":"bot-ws","msg":"websocket error","diff":0}
{"level":"INFO","name":"bot-ws","diff":1}
{"level":"INFO","name":"bot-ws","msg":"websocket closed","diff":1}
  ERROR bot +0ms
```

### Proposed fix
```
diff --git a/src/mm-client.js b/src/mm-client.js
index abb3820..1d89947 100644
--- a/src/mm-client.js
+++ b/src/mm-client.js
@@ -16,7 +16,8 @@ client.setToken(mattermostToken)

 const wsClient = new WebSocketClient();
 let matterMostURL = new URL(matterMostURLString);
-const wsUrl = `${matterMostURL.protocol === 'https:' ? 'wss' : 'ws'}://${matterMostURL.host}/api/v4/websocket`
+const pathname = matterMostURL.pathname.replace(/\/+$/, '');
+const wsUrl = `${matterMostURL.protocol === 'https:' ? 'wss' : 'ws'}://${matterMostURL.host}${pathname}/api/v4/websocket`

 new Promise((resolve, reject) => {
   wsClient.addCloseListener(connectFailCount => reject())
```

Best regards.

### PR DESCRIPTION
**Pull request by sh2**
Fix #18

### CODE REVIEW

**Comment by yGuy** [comment]
Thanks - I believe there is even an API to get the websocket url - we should probably use that one instead?

**Comment by yGuy** [comment]
Please check whether my fix works for you - I think it's the more robust fix (if it works :-)

**Comment by sh2** [comment]
Thank you for a more generic solution!
There seems to be a slight error in the code.
https://github.com/yGuy/chatgpt-mattermost-bot/commit/558f6ca52f461d8a16aa5c310b3a7cb8e6a2a45e

before
wsUrl.protocol = wsUrl.protocol === 'https' ? 'wss' : 'ws'

after
wsUrl.protocol = wsUrl.protocol === 'https:' ? 'wss' : 'ws'

**Comment by yGuy** [comment]
D'oh. Thanks. Can you please check again?

**Comment by sh2** [comment]
OK. It works fine. Thank you!

**Pull request closed without merging**
